[package]
name = "boluo_server"
version = "0.1.0"
authors = ["Quan Brew <t@ioover.net>"]
edition = "2018"
default-run = "server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "manage"
path = "src/manage.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
postgres-types = { version = "0.1.0", features = ["derive"]}
async-trait = "*"
dotenv = "*"
anyhow = "*"
once_cell = "*"
thiserror = "*"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
crc32fast = "1.2.0"
hyper = "0.13"
futures = "0.3"
regex = "1"
serde_urlencoded = "*"
cookie = "0.12.0"
time = "0.1"
ring = "*"
base64 = "*"
log = "0.4"
bincode = "1"
percent-encoding = "2.1.0"
blake3 = "*"
mime = "0.3.16"
bytes = "*"

[dependencies.serde]
version = "1.0"
features = ["derive", "rc"]

[dependencies.tokio-postgres]
version = "0.5.0"
features = ["with-chrono-0_4", "with-uuid-0_8", "with-serde_json-1"]

[dependencies.uuid]
version = "0.8"
features = ["serde", "v1", "v4"]

[dependencies.tokio]
version = "0.2.8"
features = ["full"]

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"

[dependencies.fern]
version = "0.5"
features = ["colored"]
