on: [push]

name: CI

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly

    services:
      redis:
        image: redis
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: boluo

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: Build
        run: cargo build --release

      - name: Init Database
        run: cargo run --release --bin manage init
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres/boluo

      - name: Test
        run: cargo test --release
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres/boluo
          SECRET: SOME_SECRET
          REDIS_URL: redis://redis/
          DEBUG: 1
          PORT: 3000

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            target
