name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive
        run: zip -j build.zip target/release/server target/release/manage schema.sql && zip -r build.zip migrations/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: boluo-server
          path: build.zip
