name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: boluo-server
          path: |
            schema.sql
            target/release/server
            target/release/manage
            migrations/
