name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05
          extra_nix_config: |
            trusted-public-keys = binarycache.yuru.me:/PQxFq2js4z23C4JSN6oP0kAlPpIBmDHQtxHgXJL9IM=
            substituters = http://binarycache.yuru.me
      - run: nix-build .
