name: Release
on:
  push:
    branches:
      - master

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive
        run: zip -j build.zip target/release/server target/release/manage schema.sql && zip -r build.zip migrations/

      - name: Upload to B2
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy build.zip b2:boluo-backup/
